USE studybuddy;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,

  username VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,

  password_hash VARCHAR(255) NOT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);